### ISSUE TITLE
Error when run csscomb

### ISSUE THREAD

**Issue by EmadAdly** [csscomb/csscomb.js#221]
<code>
error: CSScomb error:

C:\Users\emad\AppData\Roaming\Sublime Text 3\Packages\CSScomb JS\node_modules\csscomb\lib\csscomb.js:205

```
        throw new Error('Parsing error at ' + filename + ': ' + e.message)

              ^
```

Error: Parsing error at undefined: Please check the validity of the CSS block starting from the line #1

```
at Object.Comb.processString (C:\Users\emad\AppData\Roaming\Sublime Text 3\Packages\CSScomb JS\node_modules\csscomb\lib\csscomb.js:205:19)

at Socket.<anonymous> (C:\Users\emad\AppData\Roaming\Sublime Text 3\Packages\CSScomb JS\csscomb.js:23:37)

at Socket.EventEmitter.emit (events.js:117:20)

at _stream_readable.js:920:16

at process._tickCallback (node.js:415:13)
```

</code>

**Comment by tsclark** [comment]
I have encountered this error when selecting the style declarations without the surrounding context.
Selecting
`padding:25px 10px; font-family:'Trade Gothic', sans-serif;`
returns an error, but selecting
`#overlayHub .content{ padding:25px 10px; font-family:'Trade Gothic', sans-serif; font-size:1.3em; line-height:2em; margin-top: 40px;}`
runs successfully.
Try selecting the complete statement instead of just the content inside the braces.
