### ISSUE TITLE
3.0.0-5, indented sass: spaces at EOF throw error

### ISSUE THREAD

**Issue by afknapping** [csscomb/csscomb.js#243]
combing (without any config file):

``` sass
body
  background-color: red
  color: white
  float: left
  width: 100%
  padding: 4em

```

(on the last line are only two spaces.)

throws:

```
stack:  Error: Parsing error at test/_test-partial1.sass: Cannot read property 'type' of undefined
    at cssToAST (/usr/local/lib/node_modules/csscomb/lib/csscomb.js:464:19)
    at processString (/usr/local/lib/node_modules/csscomb/lib/csscomb.js:351:20)
    at /usr/local/lib/node_modules/csscomb/lib/csscomb.js:323:39
    at Array.0 (/usr/local/lib/node_modules/csscomb/node_modules/vow/lib/vow.js:555:56)
    at Object.callFns [as _onImmediate] (/usr/local/lib/node_modules/csscomb/node_modules/vow/lib/vow.js:1148:35)
    at processImmediate [as _immediateCallback] (timers.js:336:15)

```
##

**Comment by jdalton** [comment]
This error is no longer reproducible on the latest release 👍
