### ISSUE TITLE
Issue with space-before-selector-delimiter

### ISSUE THREAD

**Issue by anant90** [csscomb/csscomb.js#248]
Consider the following snippet of sass:

```
select, textarea, input[type="text"], input[type="password"], input[type="datetime"], input[type="datetime-local"], input[type="date"], input[type="month"], input[type="time"], input[type="week"], input[type="number"], input[type="email"], input[type="url"], input[type="search"], input[type="tel"], input[type="color"]
  display: inline-block
  width: inherit
  height: auto
  padding: 2px 8px
  margin-top: 2px
  margin-bottom: 8px
  vertical-align: baseline
  border: 1px solid $gray1
```

`csscomb`ing this file gives the expected result:

```
select,
textarea,
input[type='text'],
input[type='password'],
input[type='datetime'],
input[type='datetime-local'],
input[type='date'],
input[type='month'],
input[type='time'],
input[type='week'],
input[type='number'],
input[type='email'],
input[type='url'],
input[type='search'],
input[type='tel'],
input[type='color']
    display: inline-block

    width: inherit
    height: auto
    margin-top: 2px
    margin-bottom: 8px
    padding: 2px 8px

    vertical-align: baseline

    border: 1px solid $gray1
```

`csscomb`ing this modified file again throws the following error:

```
 ✗ csscomb dev/sass/test.sass
stack:  TypeError: Cannot read property 'length' of undefined
    at module.exports.process (/usr/local/lib/node_modules/csscomb/lib/options/space-before-selector-delimiter.js:24:42)
    at /usr/local/lib/node_modules/csscomb/lib/csscomb.js:200:21
    at Array.forEach (native)
    at processNode (/usr/local/lib/node_modules/csscomb/lib/csscomb.js:196:14)
    at /usr/local/lib/node_modules/csscomb/lib/csscomb.js:205:13
    at Array.forEach (native)
    at processNode (/usr/local/lib/node_modules/csscomb/lib/csscomb.js:196:14)
    at /usr/local/lib/node_modules/csscomb/lib/csscomb.js:205:13
    at Array.forEach (native)
    at processNode (/usr/local/lib/node_modules/csscomb/lib/csscomb.js:196:14)
```
##

**Comment by jdalton** [comment]
This is fixed in the latest csscomb release :)
