### ISSUE TITLE
3.0.0-5, SCSS: multiple classes in the same @extend throw error

### ISSUE THREAD

**Issue by denisborovikov** [csscomb/csscomb.js#257]
```
.search {
    @extend .icon, .icon-search;
}
```

Error

```
stack:  Error: Parsing error at _head.scss: Please check the validity of the CSS block starting from the line #28
    at cssToAST (/usr/local/lib/node_modules/csscomb/lib/csscomb.js:464:19)
    at processString (/usr/local/lib/node_modules/csscomb/lib/csscomb.js:351:20)
    at /usr/local/lib/node_modules/csscomb/lib/csscomb.js:323:39
    at Array.0 (/usr/local/lib/node_modules/csscomb/node_modules/vow/lib/vow.js:555:56)
    at Object.callFns [as _onImmediate] (/usr/local/lib/node_modules/csscomb/node_modules/vow/lib/vow.js:1148:35)
    at processImmediate [as _immediateCallback] (timers.js:330:15)
```
##

**Comment by jdalton** [comment]
This is fixed in the latest csscomb release 🕺
