### ISSUE TITLE
SCSS: TypeError using sort-order-fallback and leftovers with two properties with interpolation

### ISSUE THREAD

**Issue by princed** [csscomb/csscomb.js#294]
Quick example:

``` scss
$prop1: 'display'
$prop2: 'z-index'

.test {
  #{$prop1}: 'block';
  #{$prop2}: 0;
}
```

Stack trace:

``` sh
stack:  TypeError: Object interpolation,variable,ident,prop1 has no method 'match'
    at sortLeftovers (/usr/local/lib/node_modules/csscomb/lib/options/sort-order.js:240:19)
    at /usr/local/lib/node_modules/csscomb/lib/options/sort-order.js:328:24
    at Array.sort (native)
    at module.exports.process (/usr/local/lib/node_modules/csscomb/lib/options/sort-order.js:319:16)
    at /usr/local/lib/node_modules/csscomb/node_modules/csscomb-core/lib/core.js:206:21
    at Array.forEach (native)
    at processNode (/usr/local/lib/node_modules/csscomb/node_modules/csscomb-core/lib/core.js:202:14)
    at /usr/local/lib/node_modules/csscomb/node_modules/csscomb-core/lib/core.js:211:13
    at Array.forEach (native)
    at processNode (/usr/local/lib/node_modules/csscomb/node_modules/csscomb-core/lib/core.js:202:14)
```

Full test case: https://gist.github.com/princed/293af5f99b0b413a77e9
##

**Comment by jdalton** [comment]
This no longer errors on the latest csscomb release 🌮
