### ISSUE TITLE
SCSS: TypeError using element-case with selector interpolation

### ISSUE THREAD

**Issue by princed** [csscomb/csscomb.js#295]
Quick example:
```scss
$selector: '.test';

#{$selector} {
  display: none;
}
```

```sh
stack:  TypeError: Object interpolation,variable,ident,selector has no method 'toLowerCase'
    at module.exports.process (/usr/local/lib/node_modules/csscomb/lib/options/element-case.js:27:39)
    at /usr/local/lib/node_modules/csscomb/node_modules/csscomb-core/lib/core.js:206:21
    at Array.forEach (native)
    at processNode (/usr/local/lib/node_modules/csscomb/node_modules/csscomb-core/lib/core.js:202:14)
    at /usr/local/lib/node_modules/csscomb/node_modules/csscomb-core/lib/core.js:211:13
    at Array.forEach (native)
    at processNode (/usr/local/lib/node_modules/csscomb/node_modules/csscomb-core/lib/core.js:202:14)
    at /usr/local/lib/node_modules/csscomb/node_modules/csscomb-core/lib/core.js:211:13
    at Array.forEach (native)
    at processNode (/usr/local/lib/node_modules/csscomb/node_modules/csscomb-core/lib/core.js:202:14)
```

Full test case: https://gist.github.com/princed/70248210ef71c1fadb6a

**Comment by qborreda** [comment]
Maybe worth mentioning Compass uses #{headings(all)} and it fails as well ..

**Comment by Skoks** [comment]
+1

**Comment by lokywin** [comment]
+1

**Comment by alexkwa** [comment]
+1
Using Bourbon and this fails.

**Comment by sodatea** [comment]
Can't reproduce in 3.1.8, which is the most recent release. So I'd close this issue.
