### ISSUE TITLE
scss nested properties fail

### ISSUE THREAD

**Issue by llCorvinSll** [csscomb/csscomb.js#319]
nested properties in scss syntax throw error

http://sass-lang.com/documentation/file.SASS_REFERENCE.html#nested_properties

```
@import '../../helpers/__helpers';

.funky {
  font: {
    family: fantasy;
    size: 30em;
    weight: bold;
  }
}
```

```
stack:  TypeError: Cannot read property '0' of undefined
    at module.exports.process (.../csscomb.js/lib/options/space-before-opening-brace.js:52:36)
    at .../csscomb.js/node_modules/csscomb-core/lib/core.js:206:21
    at Array.forEach (native)
    at processNode (../csscomb.js/node_modules/csscomb-core/lib/core.js:202:14)
    at .../csscomb.js/node_modules/csscomb-core/lib/core.js:211:13
    at Array.forEach (native)
    at processNode (.../csscomb.js/node_modules/csscomb-core/lib/core.js:202:14)
    at .../csscomb.js/node_modules/csscomb-core/lib/core.js:211:13
    at Array.forEach (native)
    at processNode (.../csscomb.js/node_modules/csscomb-core/lib/core.js:202:14)
```

package versions 

```
commander@2.0.0
csscomb-core@2.0.3
gonzales-pe@3.0.0-10
jscs@1.4.5
jshint@2.3.0
jshint-groups@0.5.3
mocha@1.14.0
vow@0.4.4
```

**Comment by qborreda** [comment]
+1

**Comment by tonyganch** [comment]
Should be fixed in `dev` branch
