### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by ryanaltvater** [csscomb/csscomb.js#333]
I'm having an issue running the Gulp plugin for CSScomb that I can't seem to figure out for the life of me, and was hoping someone else could take a look and maybe shed some light. I posted this issue on the plugin's GitHub, but there's more of an audience here and was hoping to get more eyes on it. Thank you in advance!

<pre>events.js:72
        throw er; // Unhandled 'error' event
              ^
TypeError: Cannot read property '0' of undefined
    at module.exports.process (/Users/raltvater/Sites/www-static/node_modules/gulp-csscomb/node_modules/csscomb/lib/options/eof-newline.js:16:26)
    at /Users/raltvater/Sites/www-static/node_modules/gulp-csscomb/node_modules/csscomb/node_modules/csscomb-core/lib/core.js:206:21
    at Array.forEach (native)
    at processNode (/Users/raltvater/Sites/www-static/node_modules/gulp-csscomb/node_modules/csscomb/node_modules/csscomb-core/lib/core.js:202:14)
    at /Users/raltvater/Sites/www-static/node_modules/gulp-csscomb/node_modules/csscomb/node_modules/csscomb-core/lib/core.js:189:13
    at Array.forEach (native)
    at processTree (/Users/raltvater/Sites/www-static/node_modules/gulp-csscomb/node_modules/csscomb/node_modules/csscomb-core/lib/core.js:188:19)
    at processString (/Users/raltvater/Sites/www-static/node_modules/gulp-csscomb/node_modules/csscomb/node_modules/csscomb-core/lib/core.js:415:16)
    at DestroyableTransform._transform (/Users/raltvater/Sites/www-static/node_modules/gulp-csscomb/index.js:65:27)
    at DestroyableTransform.Transform._read (/Users/raltvater/Sites/www-static/node_modules/gulp-csscomb/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)</pre>

**Comment by leonko** [comment]
I has same error
```
» cat test.sass
.page-sidebar
  background #ccc
```
```
» csscomb -v  -l test.sass
stack:  TypeError: Cannot read property '0' of undefined
    at module.exports.process (/usr/local/lib/node_modules/csscomb/lib/options/eof-newline.js:16:26)
    at /usr/local/lib/node_modules/csscomb/node_modules/csscomb-core/lib/core.js:206:21
    at Array.forEach (native)
    at processNode (/usr/local/lib/node_modules/csscomb/node_modules/csscomb-core/lib/core.js:202:14)
    at /usr/local/lib/node_modules/csscomb/node_modules/csscomb-core/lib/core.js:189:13
```

**Comment by tonyganch** [comment]
@ryanaltvater @lightningtgc, this should be fixed in `dev` branch.
@leonko, that's a parsing error actually, I've opened an issue here: https://github.com/tonyganch/gonzales-pe/issues/62
