### ISSUE TITLE
Won't work once installed. Broken Pipe error.

### ISSUE THREAD

**Issue by insidesin** [csscomb/csscomb.js#347]
Sublime Text 3, Nodejs installed from the official website.

Not sure what I'm doing wrong, the error I get is:

`Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 549, in run_
    return self.run(edit)
  File "C:\Users\Jacksane\AppData\Roaming\Sublime Text 3\Packages\CSScomb\CSScomb.py", line 27, in run
    combed = self.comb(originalBuffer, syntax, config)
  File "C:\Users\Jacksane\AppData\Roaming\Sublime Text 3\Packages\CSScomb\CSScomb.py", line 49, in comb
    stdout, stderr = p.communicate(input=css.encode('utf-8'))
  File "./subprocess.py", line 928, in communicate
  File "./subprocess.py", line 1206, in _communicate
BrokenPipeError: [Errno 32] Broken pipe`
##

**Comment by LEXUS33** [comment]
Извиняюсь если не сюда пишу..
Плагин не работает.Sublime Text 3. Windows 7.
Установлен через package control.

При попытке использования выдает :
![1](https://cloud.githubusercontent.com/assets/6703590/6318479/8c53e946-baae-11e4-9f84-12eabb4ea1d2.PNG)

Точно так же установленный плагин на fedor'ke работает отлично.

**Comment by jdalton** [comment]
Please report the issue to [sublime-csscomb](https://github.com/csscomb/sublime-csscomb) if it is still a problem.
