### ISSUE TITLE
CLI should recognize stdin for input

### ISSUE THREAD

**Issue by lkraav** [csscomb/csscomb.js#351]
v3.0.4

Currently stdin is not handled

```
$ cat style.less | csscomb -c /etc/csscomb.json -
Path - was not found.
```

**Comment by channikhabra** [comment]
+1

**Comment by tonyganch** [comment]
Should be fixed in `dev`

**Comment by StreetStrider** [comment]
```sh
$ csscomb --version
3.1.8
```
```sh
$ node-sass quarks-all/test/test.scss | csscomb                    
No input paths specified

  Usage: csscomb [options] <file ...>

  Options:

    -h, --help           output usage information
    -V, --version        output the version number
    -v, --verbose        verbose mode
    -c, --config [path]  configuration file path
    -d, --detect         detect mode (would return detected options)
    -l, --lint           in case some fixes needed returns an error

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at Object.exports._errnoException (util.js:874:11)
    at exports._exceptionWithHostPort (util.js:897:20)
    at WriteWrap.afterWrite (net.js:763:14)
```
```sh
$ lessc quarks-all/test/test.less | csscomb
No input paths specified

  Usage: csscomb [options] <file ...>

  Options:

    -h, --help           output usage information
    -V, --version        output the version number
    -v, --verbose        verbose mode
    -c, --config [path]  configuration file path
    -d, --detect         detect mode (would return detected options)
    -l, --lint           in case some fixes needed returns an error
```

**Comment by jdalton** [comment]
We need to add a way to specify the syntax of the input.
