### ISSUE TITLE
dev branch is broken?

### ISSUE THREAD

**Issue by francoismassart** [csscomb/csscomb.js#358]
Quick question.
I read the in [guidelines for contributing](https://github.com/csscomb/csscomb.js/blob/master/CONTRIBUTING.md) that we must develop starting from the branch `dev` and not from the `master` branch... No problem with the principle but...

When using the `dev` branch, if I run `npm test` before chaning any files, I get plenty of errors:
```
  142 passing (570ms)
  174 pending
  111 failing
```
Here is the first 5 failing test output:
```
1) options/always-semicolon Should add semicolon for last property if missing. Test 1:
     TypeError: Object #<Object> has no method 'createNode'
      at module.exports.process (/Users/francois/Downloads/csscomb.js/lib/options/always-semicolon.js:53:38)
      at Object.Node.map (/Users/francois/Downloads/csscomb.js/node_modules/csscomb-core/node_modules/gonzales-pe/lib/node.js:111:9)
      at /Users/francois/Downloads/csscomb.js/node_modules/csscomb-core/node_modules/gonzales-pe/lib/node.js:117:22
      at Array.forEach (native)
      at Object.Node.map (/Users/francois/Downloads/csscomb.js/node_modules/csscomb-core/node_modules/gonzales-pe/lib/node.js:115:22)
      at /Users/francois/Downloads/csscomb.js/node_modules/csscomb-core/node_modules/gonzales-pe/lib/node.js:117:22
      at Array.forEach (native)
      at Object.Node.map (/Users/francois/Downloads/csscomb.js/node_modules/csscomb-core/node_modules/gonzales-pe/lib/node.js:115:22)
      at /Users/francois/Downloads/csscomb.js/node_modules/csscomb-core/lib/core.js:189:18
      at Array.forEach (native)

  2) options/always-semicolon Should add semicolon for last property if missing. Test 2:
     TypeError: Object #<Object> has no method 'createNode'
      at module.exports.process (/Users/francois/Downloads/csscomb.js/lib/options/always-semicolon.js:53:38)
      at Object.Node.map (/Users/francois/Downloads/csscomb.js/node_modules/csscomb-core/node_modules/gonzales-pe/lib/node.js:111:9)
      at /Users/francois/Downloads/csscomb.js/node_modules/csscomb-core/node_modules/gonzales-pe/lib/node.js:117:22
      at Array.forEach (native)
      at Object.Node.map (/Users/francois/Downloads/csscomb.js/node_modules/csscomb-core/node_modules/gonzales-pe/lib/node.js:115:22)
      at /Users/francois/Downloads/csscomb.js/node_modules/csscomb-core/node_modules/gonzales-pe/lib/node.js:117:22
      at Array.forEach (native)
      at Object.Node.map (/Users/francois/Downloads/csscomb.js/node_modules/csscomb-core/node_modules/gonzales-pe/lib/node.js:115:22)
      at /Users/francois/Downloads/csscomb.js/node_modules/csscomb-core/lib/core.js:189:18
      at Array.forEach (native)

  3) options/always-semicolon Should add semicolon for last property if missing. Test 3:
     TypeError: Object #<Object> has no method 'createNode'
      at module.exports.process (/Users/francois/Downloads/csscomb.js/lib/options/always-semicolon.js:53:38)
      at Object.Node.map (/Users/francois/Downloads/csscomb.js/node_modules/csscomb-core/node_modules/gonzales-pe/lib/node.js:111:9)
      at /Users/francois/Downloads/csscomb.js/node_modules/csscomb-core/node_modules/gonzales-pe/lib/node.js:117:22
      at Array.forEach (native)
      at Object.Node.map (/Users/francois/Downloads/csscomb.js/node_modules/csscomb-core/node_modules/gonzales-pe/lib/node.js:115:22)
      at /Users/francois/Downloads/csscomb.js/node_modules/csscomb-core/node_modules/gonzales-pe/lib/node.js:117:22
      at Array.forEach (native)
      at Object.Node.map (/Users/francois/Downloads/csscomb.js/node_modules/csscomb-core/node_modules/gonzales-pe/lib/node.js:115:22)
      at /Users/francois/Downloads/csscomb.js/node_modules/csscomb-core/lib/core.js:189:18
      at Array.forEach (native)

  4) options/always-semicolon Should add semicolon for last property if missing. Test 4:
     TypeError: Object #<Object> has no method 'createNode'
      at module.exports.process (/Users/francois/Downloads/csscomb.js/lib/options/always-semicolon.js:53:38)
      at Object.Node.map (/Users/francois/Downloads/csscomb.js/node_modules/csscomb-core/node_modules/gonzales-pe/lib/node.js:111:9)
      at /Users/francois/Downloads/csscomb.js/node_modules/csscomb-core/node_modules/gonzales-pe/lib/node.js:117:22
      at Array.forEach (native)
      at Object.Node.map (/Users/francois/Downloads/csscomb.js/node_modules/csscomb-core/node_modules/gonzales-pe/lib/node.js:115:22)
      at /Users/francois/Downloads/csscomb.js/node_modules/csscomb-core/node_modules/gonzales-pe/lib/node.js:117:22
      at Array.forEach (native)
      at Object.Node.map (/Users/francois/Downloads/csscomb.js/node_modules/csscomb-core/node_modules/gonzales-pe/lib/node.js:115:22)
      at /Users/francois/Downloads/csscomb.js/node_modules/csscomb-core/lib/core.js:189:18
      at Array.forEach (native)

  5) options/always-semicolon Should add semicolon for last property if missing. Test 5:
     TypeError: Object #<Object> has no method 'createNode'
      at module.exports.process (/Users/francois/Downloads/csscomb.js/lib/options/always-semicolon.js:53:38)
      at Object.Node.map (/Users/francois/Downloads/csscomb.js/node_modules/csscomb-core/node_modules/gonzales-pe/lib/node.js:111:9)
      at /Users/francois/Downloads/csscomb.js/node_modules/csscomb-core/node_modules/gonzales-pe/lib/node.js:117:22
      at Array.forEach (native)
      at Object.Node.map (/Users/francois/Downloads/csscomb.js/node_modules/csscomb-core/node_modules/gonzales-pe/lib/node.js:115:22)
      at /Users/francois/Downloads/csscomb.js/node_modules/csscomb-core/node_modules/gonzales-pe/lib/node.js:117:22
      at Array.forEach (native)
      at Object.Node.map (/Users/francois/Downloads/csscomb.js/node_modules/csscomb-core/node_modules/gonzales-pe/lib/node.js:115:22)
      at /Users/francois/Downloads/csscomb.js/node_modules/csscomb-core/lib/core.js:189:18
      at Array.forEach (native)
```

Is this normal?

**Comment by francoismassart** [comment]
After several attempts, I believe it was just an issue with the `node_modules`folder.

I deleted the `node_modules` folder then in Terminal, I went in the working directory of CSS Comb and did a fresh install of the node modules with `npm install`.

Now the tests are running:
```
npm test

> csscomb@3.0.4 test /Users/francois/Downloads/csscomb.js
> ./node_modules/.bin/jshint-groups && ./node_modules/.bin/jscs . && node test/mocha

lint group "js"
lint group "test"
No code style errors found.

  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․

  253 passing (670ms)
  174 pending
```
