### ISSUE TITLE
Error on empty class closed on the same line

### ISSUE THREAD

**Issue by antoniancu** [csscomb/csscomb.js#362]
I run into the following CSScomb error:

```
/Users/computer1411/Library/Application Support/Sublime Text 3/Packages/CSScomb/node_modules/csscomb/lib/options/space-after-opening-brace.js:25
        if (node[0][0] === 's') {
                   ^
TypeError: Cannot read property '0' of undefined
    at module.exports.process (/Users/computer1411/Library/Application Support/Sublime Text 3/Packages/CSScomb/node_modules/csscomb/lib/options/space-after-opening-brace.js:25:20)
    at /Users/computer1411/Library/Application Support/Sublime Text 3/Packages/CSScomb/node_modules/csscomb/node_modules/csscomb-core/lib/core.js:206:21
    at Array.forEach (native)
    at processNode (/Users/computer1411/Library/Application Support/Sublime Text 3/Packages/CSScomb/node_modules/csscomb/node_modules/csscomb-core/lib/core.js:202:14)
    at /Users/computer1411/Library/Application Support/Sublime Text 3/Packages/CSScomb/node_modules/csscomb/node_modules/csscomb-core/lib/core.js:211:13
    at Array.forEach (native)
    at processNode (/Users/computer1411/Library/Application Support/Sublime Text 3/Packages/CSScomb/node_modules/csscomb/node_modules/csscomb-core/lib/core.js:202:14)
    at /Users/computer1411/Library/Application Support/Sublime Text 3/Packages/CSScomb/node_modules/csscomb/node_modules/csscomb-core/lib/core.js:211:13
    at Array.forEach (native)
    at processNode (/Users/computer1411/Library/Application Support/Sublime Text 3/Packages/CSScomb/node_modules/csscomb/node_modules/csscomb-core/lib/core.js:202:14)
```

I have narrowed it down to this line:
```
 > a {}
```

This should be an easy fix as it only craps out when the the brackets are on the same line. The following does not throw an error: 
```
 > a {
}
```

**Comment by hudochenkov** [comment]
Related to #289.
