### ISSUE TITLE
space-between-declarations fails on media queries

### ISSUE THREAD

**Issue by aymanrady** [csscomb/csscomb.js#378]
options/space-between-declarations.js throws error while parsing css file with media query
```
TypeError: Object ( has no method 'is'
    at module.exports.process (/srv/www/csscomb-testcase/node_modules/csscomb/lib/options/space-between-declarations.js:71:50)
    at Object.Node.map (/srv/www/csscomb-testcase/node_modules/csscomb/node_modules/gonzales-pe/lib/node.js:111:9)
    at /srv/www/csscomb-testcase/node_modules/csscomb/node_modules/gonzales-pe/lib/node.js:117:22
    at Array.forEach (native)
    at Object.Node.map (/srv/www/csscomb-testcase/node_modules/csscomb/node_modules/gonzales-pe/lib/node.js:115:22)
    at /srv/www/csscomb-testcase/node_modules/csscomb/node_modules/gonzales-pe/lib/node.js:117:22
    at Array.forEach (native)
    at Object.Node.map (/srv/www/csscomb-testcase/node_modules/csscomb/node_modules/gonzales-pe/lib/node.js:115:22)
    at /srv/www/csscomb-testcase/node_modules/csscomb/node_modules/gonzales-pe/lib/node.js:117:22
    at Array.forEach (native)
```
the problem is with this code **options/space-between-declarations.js#L71**
```js
if (!node.get(i) || !node.get(i).is('declarationDelimiter')) continue;
```
gonzales-pe doesn't return a Node object for `(` & `)`

[simplified test-case](https://github.com/aymanrady/csscomb-media-bug)

**Comment by tonyganch** [comment]
Thank you! Will take a look

**Comment by tonyganch** [comment]
Fixed in `csscomb@3.1.1`

**Comment by Swerner1975** [comment]
Same problem here on other file (with the new csscomb):

TypeError: Object appVariantsForm has no method 'is'
    at processNode (d:\gulp-project\node_modules\gulp-csscomb\node_modules\csscomb\lib\options\block-indent.js:24:19)
    at processNode (d:\gulp-project\node_modules\gulp-csscomb\node_modules\csscomb\lib\options\block-indent.js:26:13)
    at processNode (d:\gulp-project\node_modules\gulp-csscomb\node_modules\csscomb\lib\options\block-indent.js:26:13)
    at processNode (d:\gulp-project\node_modules\gulp-csscomb\node_modules\csscomb\lib\options\block-indent.js:26:13)
    at processNode (d:\gulp-project\node_modules\gulp-csscomb\node_modules\csscomb\lib\options\block-indent.js:26:13)
    at process (d:\gulp-project\node_modules\gulp-csscomb\node_modules\csscomb\lib\options\block-indent.js:102:13)
    at Object.Node.map (d:\gulp-project\node_modules\gulp-csscomb\node_modules\csscomb\node_modules\gonzales-pe\lib\node.js:111:9)
    at d:\gulp-project\node_modules\gulp-csscomb\node_modules\csscomb\node_modules\csscomb-core\lib\core.js:189:18
    at Array.forEach (native)
    at processTree (d:\gulp-project\node_modules\gulp-csscomb\node_modules\csscomb\node_modules\csscomb-core\lib\core.js:188:19)

**Comment by tonyganch** [comment]
@Swerner1975, can you please share your code so I can write a test?

**Comment by Swerner1975** [comment]
Look at issue #379 :)
