### ISSUE TITLE
Error with #ClassName

### ISSUE THREAD

**Issue by Swerner1975** [csscomb/csscomb.js#379]
This CSS Code: 

#appVariantsForm .foLi {
...
}

or 

.pageArea #header { 
... 
}

throws the following error:

TypeError: Object appVariantsForm has no method 'is'
    at processNode (d:\gulp-project\node_modules\gulp-csscomb\node_modules\csscomb\lib\options\block-indent.js:24:19)
    at processNode (d:\gulp-project\node_modules\gulp-csscomb\node_modules\csscomb\lib\options\block-indent.js:26:13)
    at processNode (d:\gulp-project\node_modules\gulp-csscomb\node_modules\csscomb\lib\options\block-indent.js:26:13)
    at processNode (d:\gulp-project\node_modules\gulp-csscomb\node_modules\csscomb\lib\options\block-indent.js:26:13)
    at processNode (d:\gulp-project\node_modules\gulp-csscomb\node_modules\csscomb\lib\options\block-indent.js:26:13)
    at process (d:\gulp-project\node_modules\gulp-csscomb\node_modules\csscomb\lib\options\block-indent.js:102:13)
    at Object.Node.map (d:\gulp-project\node_modules\gulp-csscomb\node_modules\csscomb\node_modules\gonzales-pe\lib\node.js:111:9)
    at d:\gulp-project\node_modules\gulp-csscomb\node_modules\csscomb\node_modules\csscomb-core\lib\core.js:189:18
    at Array.forEach (native)
    at processTree (d:\gulp-project\node_modules\gulp-csscomb\node_modules\csscomb\node_modules\csscomb-core\lib\core.js:188:19)

Seems the hash is the problem ...

**Comment by tonyganch** [comment]
Thank you so much!
Should be fixed in `csscomb@3.1.2`
