### ISSUE TITLE
Cannot call method 'is' of undefined

### ISSUE THREAD

**Issue by Swerner1975** [csscomb/csscomb.js#382]
Don't know wich CSS Code this throws.... but we get now following error...

--- 

events.js:72
        throw er; // Unhandled 'error' event
              ^
TypeError: Cannot call method 'is' of undefined
    at /opt/tsip-build/data/jenkins-home/workspace/Gulp_Project_Parameterized/bece/design/trunk/clickdummy/gulp-project/node_modules/csscomb/lib/options/space-before-combinator.js:27:47
    at Object.Node.forEach (/opt/tsip-build/data/jenkins-home/workspace/Gulp_Project_Parameterized/bece/design/trunk/clickdummy/gulp-project/node_modules/csscomb/node_modules/gonzales-pe/lib/node.js:63:17)
    at /opt/tsip-build/data/jenkins-home/workspace/Gulp_Project_Parameterized/bece/design/trunk/clickdummy/gulp-project/node_modules/csscomb/lib/options/space-before-combinator.js:26:28
    at Object.Node.forEach (/opt/tsip-build/data/jenkins-home/workspace/Gulp_Project_Parameterized/bece/design/trunk/clickdummy/gulp-project/node_modules/csscomb/node_modules/gonzales-pe/lib/node.js:63:17)
    at module.exports.process (/opt/tsip-build/data/jenkins-home/workspace/Gulp_Project_Parameterized/bece/design/trunk/clickdummy/gulp-project/node_modules/csscomb/lib/options/space-before-combinator.js:25:14)
    at Object.Node.map (/opt/tsip-build/data/jenkins-home/workspace/Gulp_Project_Parameterized/bece/design/trunk/clickdummy/gulp-project/node_modules/csscomb/node_modules/gonzales-pe/lib/node.js:111:9)
    at /opt/tsip-build/data/jenkins-home/workspace/Gulp_Project_Parameterized/bece/design/trunk/clickdummy/gulp-project/node_modules/csscomb/node_modules/gonzales-pe/lib/node.js:117:22
    at Array.forEach (native)
    at Object.Node.map (/opt/tsip-build/data/jenkins-home/workspace/Gulp_Project_Parameterized/bece/design/trunk/clickdummy/gulp-project/node_modules/csscomb/node_modules/gonzales-pe/lib/node.js:115:22)
    at /opt/tsip-build/data/jenkins-home/workspace/Gulp_Project_Parameterized/bece/design/trunk/clickdummy/gulp-project/node_modules/csscomb/node_modules/gonzales-pe/lib/node.js:117:22

---

**Comment by tonyganch** [comment]
Can you please tell me csscomb version?

**Comment by Swerner1975** [comment]
csscomb@3.1.2 node_modules/csscomb
├── commander@2.0.0
├── vow@0.4.4
├── csscomb-core@3.0.0-1 (minimatch@0.2.12, vow-fs@0.3.2)
└── gonzales-pe@3.0.0-28

gulp-csscomb@3.0.3 node_modules/gulp-csscomb
└── through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)

**Comment by tonyganch** [comment]
Can you update to 3.1.3?

**Comment by Swerner1975** [comment]
ZHX! Work in 3.1.3.
