### ISSUE TITLE
CSScomb for formatting a .less file

### ISSUE THREAD

**Issue by raky291** [csscomb/csscomb.js#475]
I'm using CSScomb for formatting a .less file, just copy my code and run the beautifier.

```
@grid-width15:  round(@grid-gutter-width / 2);
@grid-width10: round((@grid-gutter-width / 2) - 5 );
```

```
Unsupported beautification result 'Parsing error: Please check the validity of the block starting from line #3

1 | @grid-width15: round(@grid-gutter-width / 2); 2 | @grid-width10: round((@grid-gutter-width / 2) - 5 );

Gonzales PE version: 3.0.0-28 Syntax: less'.
Unsupported beautification result 'Parsing error: Please check the validity of the block starting from line #3
1 | @grid-width15:  round(@grid-gutter-width / 2);
2 | @grid-width10: round((@grid-gutter-width / 2) - 5 );
Gonzales PE version: 3.0.0-28
Syntax: less'.
Hide Stack Trace
Error: Unsupported beautification result 'Parsing error: Please check the validity of the block starting from line #3
1 | @grid-width15:  round(@grid-gutter-width / 2);
2 | @grid-width10: round((@grid-gutter-width / 2) - 5 );
Gonzales PE version: 3.0.0-28
Syntax: less'.
    at beautifyCompleted (file:///C:/Users/nRaky/.atom/packages/atom-beautify/src/beautify.coffee:135:21)
    at tryCatcher (C:\Users\nRaky\.atom\packages\atom-beautify\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\nRaky\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:504:31)
    at Promise._settlePromise (C:\Users\nRaky\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:561:18)
    at Promise._settlePromise0 (C:\Users\nRaky\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:606:10)
    at Promise._settlePromises (C:\Users\nRaky\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:681:18)
    at Async._drainQueue (C:\Users\nRaky\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:138:16)
    at Async._drainQueues (C:\Users\nRaky\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:148:10)
    at Async.drainQueues (C:\Users\nRaky\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:17:14)
```

Original issue: https://github.com/Glavin001/atom-beautify/issues/1098
##

**Comment by jdalton** [comment]
This is fixed in the latest release of csscomb 😄
