### ISSUE TITLE
Crashing with complicated less selector

### ISSUE THREAD

**Issue by petrchutny** [csscomb/csscomb.js#589]
I have selected CSSComb in Atom to beautify the code, and it seems to have crashed on a complicated CSS selector.

Here is the error message:

```
Unsupported beautification result 'Parsing error: Please check validity of the block starting from line #703 CSScomb Core version: 4.2.0

701 | } 703*| button[class^="ch-button-"], 704 | a[class^="ch-button"]:not([class$="alternative"]), 705 | {

Syntax: less Gonzales PE version: 3.4.7'.
Unsupported beautification result 'Parsing error: Please check validity of the block starting from line #703
CSScomb Core version: 4.2.0
701 | }
703*| button[class^="ch-button-"],
704 | a[class^="ch-button"]:not([class$="alternative"]),
705 |  {
Syntax: less
Gonzales PE version: 3.4.7'.
Hide Stack Trace
Error: Unsupported beautification result 'Parsing error: Please check validity of the block starting from line #703
CSScomb Core version: 4.2.0
701 | }
703*| button[class^="ch-button-"],
704 | a[class^="ch-button"]:not([class$="alternative"]),
705 |  {
Syntax: less
Gonzales PE version: 3.4.7'.
    at beautifyCompleted (/Users/petrchutny/.atom/packages/atom-beautify/src/beautify.coffee:140:17)
    at tryCatcher (/Users/petrchutny/.atom/packages/atom-beautify/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/petrchutny/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/petrchutny/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/petrchutny/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/petrchutny/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/Users/petrchutny/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/petrchutny/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:143:10)
    at Async.drainQueues (/Users/petrchutny/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:17:14)
    at <anonymous>
```

**Comment by tonyganch** [comment]
Hi @petrchutny, the issue is in the LESS snippet above, you have a trailing comma before opening bracket which makes code invalid from LESS point of view.
