### ISSUE TITLE
CSScomb error: (node:21687) UnhandledPromiseRejectionWarning: TypeError: ast.remove is not a function

### ISSUE THREAD

**Issue by pengzheng2** [csscomb/csscomb.js#594]
Does anyone know why and how to fix?

CSScomb error:
(node:21687) UnhandledPromiseRejectionWarning: TypeError: ast.remove is not a function
    at /Users/zachcheng/Library/Application Support/Sublime Text 3/Packages/CSScomb/node_modules/csscomb/lib/options/block-indent.js:48:13
    at Node.eachFor (/Users/zachcheng/Library/Application Support/Sublime Text 3/Packages/CSScomb/node_modules/csscomb/node_modules/gonzales-pe/lib/gonzales.js:129:83)
    at Plugin.process (/Users/zachcheng/Library/Application Support/Sublime Text 3/Packages/CSScomb/node_modules/csscomb/lib/options/block-indent.js:44:9)
    at /Users/zachcheng/Library/Application Support/Sublime Text 3/Packages/CSScomb/node_modules/csscomb/lib/core.js:384:14
    at Array.forEach (<anonymous>)
    at Comb._processTree (/Users/zachcheng/Library/Application Support/Sublime Text 3/Packages/CSScomb/node_modules/csscomb/lib/core.js:383:8)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:21687) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:21687) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by seezee** [comment]
Similar problem. Just updated to latest version hoping it would fix but still getting:

`(node:96346) UnhandledPromiseRejectionWarning: TypeError: ast.remove is not a function
    at /usr/local/lib/node_modules/csscomb/lib/options/block-indent.js:48:13
    at Node.eachFor (/usr/local/lib/node_modules/csscomb/node_modules/gonzales-pe/lib/gonzales.js:129:83)
    at Plugin.process (/usr/local/lib/node_modules/csscomb/lib/options/block-indent.js:44:9)
    at /usr/local/lib/node_modules/csscomb/lib/core.js:384:14
    at Array.forEach (<anonymous>)
    at Comb._processTree (/usr/local/lib/node_modules/csscomb/lib/core.js:383:8)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
(node:96346) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:96346) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by tonyganch** [comment]
Hi @seezee, i haven't published the fix as a new version to npm yet. I'm planning to do that in next couple of days, so please hold on a bit more.

**Comment by tonyganch** [comment]
@seezee, published as v4.3.0

**Comment by seezee** [comment]
> @seezee, published as v4.3.0

Thanks. I'll try again once it's pushed to NPM.
